import { addDays, todayISO } from "./calendar";
import type { Database, Task, TimeSession, User } from "./types";

/**
 * Demo dataset. Dates are generated relative to "today" so the app always
 * opens on a plausible, in-flight week rather than a stale snapshot.
 */

const T = todayISO();
const d = (n: number) => addDays(T, n);

/** Timestamp helper: n days from today at hh:mm local. */
function ts(dayOffset: number, hh: number, mm = 0): string {
  const base = new Date();
  base.setDate(base.getDate() + dayOffset);
  base.setHours(hh, mm, 0, 0);
  return base.toISOString();
}

const users: User[] = [
  {
    id: "u-super",
    fullName: "Rohan Deshmukh",
    email: "super@synovative.in",
    password: "super123",
    role: "super_admin",
    departments: ["Project Managers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-240, 10),
  },
  {
    id: "u-admin",
    fullName: "Priya Nair",
    email: "admin@synovative.in",
    password: "admin123",
    role: "admin",
    departments: ["Project Managers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-230, 10),
  },
  {
    id: "u-manager",
    fullName: "Aditya Kulkarni",
    email: "manager@synovative.in",
    password: "manager123",
    role: "manager",
    departments: ["Project Managers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-220, 10),
  },
  {
    id: "u-hr",
    fullName: "Sneha Iyer",
    email: "hr@synovative.in",
    password: "hr123",
    role: "hr_admin",
    departments: ["Human Resources & Admin"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-215, 10),
  },
  {
    id: "u-tl-design",
    fullName: "Karan Mehta",
    email: "karan@synovative.in",
    password: "karan123",
    role: "team_leader",
    departments: [
      "Graphic Designers",
      "Content Writers / Copywriters / Brand Strategists",
    ],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-200, 10),
  },
  {
    id: "u-tl-video",
    fullName: "Nikhil Patil",
    email: "nikhil@synovative.in",
    password: "nikhil123",
    role: "team_leader",
    departments: [
      "Videographers / Video Editors / Motion Graphics",
      "3D Artists",
    ],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-198, 10),
  },
  {
    id: "u-finance",
    fullName: "Meera Joshi",
    email: "finance@synovative.in",
    password: "finance123",
    role: "team_member",
    departments: ["Accounts & Finance"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-190, 10),
  },
  {
    id: "u-design-1",
    fullName: "Ashirwad Agrawal",
    email: "ashirwad@synovative.in",
    password: "ashirwad123",
    role: "team_member",
    departments: ["Graphic Designers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-180, 10),
  },
  {
    id: "u-design-2",
    fullName: "Rahul Agarwal",
    email: "rahul@synovative.in",
    password: "rahul123",
    role: "team_member",
    departments: ["Graphic Designers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-175, 10),
  },
  {
    id: "u-video-1",
    fullName: "Tanvi Shetty",
    email: "tanvi@synovative.in",
    password: "tanvi123",
    role: "team_member",
    departments: ["Videographers / Video Editors / Motion Graphics"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-170, 10),
  },
  {
    id: "u-smm-1",
    fullName: "Farhan Qureshi",
    email: "farhan@synovative.in",
    password: "farhan123",
    role: "team_member",
    departments: ["Social Media Marketing"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-165, 10),
  },
  {
    id: "u-perf-1",
    fullName: "Divya Raut",
    email: "divya@synovative.in",
    password: "divya123",
    role: "team_member",
    departments: ["Performance Marketers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-160, 10),
  },
  {
    id: "u-web-1",
    fullName: "Sameer Bhatt",
    email: "sameer@synovative.in",
    password: "sameer123",
    role: "team_member",
    departments: ["Website Developers"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-155, 10),
  },
  {
    id: "u-3d-1",
    fullName: "Pooja Sawant",
    email: "pooja@synovative.in",
    password: "pooja123",
    role: "team_member",
    departments: ["3D Artists"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-150, 10),
  },
  {
    id: "u-content-1",
    fullName: "Ira Chatterjee",
    email: "ira@synovative.in",
    password: "ira123",
    role: "team_member",
    departments: ["Content Writers / Copywriters / Brand Strategists"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-148, 10),
  },
  {
    id: "u-bd-1",
    fullName: "Vikram Salvi",
    email: "vikram@synovative.in",
    password: "vikram123",
    role: "team_member",
    departments: ["Business Development Executives"],
    active: true,
    mustChangePassword: false,
    createdAt: ts(-140, 10),
  },
];

const vendors: Database["vendors"] = [
  {
    id: "v-1",
    name: "SkyLens Aerials",
    serviceType: "Drone Shoot and Edit",
    contactPerson: "Imran Shaikh",
    phone: "+91 98200 41122",
    email: "ops@skylensaerials.in",
    rate: 18000,
    notes: "DGCA-certified pilots. Andheri based, covers all of MMR.",
  },
  {
    id: "v-2",
    name: "Frame Nine Studios",
    serviceType: "Video Shoot & Editing",
    contactPerson: "Ritika Bansal",
    phone: "+91 99303 77410",
    email: "hello@framenine.studio",
    rate: 35000,
    notes: "Full crew + gear for property walkthrough films.",
  },
  {
    id: "v-3",
    name: "Cast Mumbai",
    serviceType: "Videography & Photography",
    contactPerson: "Neha Kamble",
    phone: "+91 98191 22087",
    email: "bookings@castmumbai.com",
    rate: 12000,
    notes: "Model casting for property shoots. Per-model day rate.",
  },
  {
    id: "v-4",
    name: "Signpost Media",
    serviceType: "Hoarding Printing and Installation",
    contactPerson: "Dilip Rane",
    phone: "+91 93242 55018",
    email: "accounts@signpostmedia.in",
    rate: 65000,
    notes: "Flex printing + installation across Western suburbs.",
  },
  {
    id: "v-5",
    name: "VoiceCraft India",
    serviceType: "Voice-Over",
    contactPerson: "Anand Rao",
    phone: "+91 90040 11889",
    email: "studio@voicecraft.in",
    rate: 6500,
    notes: "Hindi / Marathi / English artists, 24h turnaround.",
  },
];

const projects: Database["projects"] = [
  {
    id: "p-1",
    name: "Lodha Amara — Launch Campaign",
    color: "#5F3CA7",
    clientName: "Lodha Group",
    services: [
      "Social Media Management Services",
      "Project Launch Campaign Design",
      "Facebook Ads Campaign",
      "Drone Shoot and Edit",
    ],
    startDate: d(-24),
    deadline: d(28),
    description:
      "Full launch package for the Amara Thane tower — creatives, launch film, paid media and hoardings for the first sales window.",
    status: "Active",
    priority: "Critical",
    leaderId: "u-manager",
    memberIds: [
      "u-design-1",
      "u-design-2",
      "u-video-1",
      "u-smm-1",
      "u-perf-1",
      "u-content-1",
    ],
    createdBy: "u-admin",
    createdAt: ts(-24, 11),
  },
  {
    id: "p-2",
    name: "Runwal Gardens — Monthly Retainer",
    color: "#4B8FE6",
    clientName: "Runwal Developers",
    services: [
      "Monthly Retainer",
      "Social Media Management Services",
      "Creative Post",
      "Reel Editing",
    ],
    startDate: d(-40),
    deadline: d(50),
    description:
      "Ongoing social retainer: 16 static posts, 8 reels and community management per month.",
    status: "Active",
    priority: "Medium",
    leaderId: "u-tl-design",
    memberIds: ["u-design-2", "u-smm-1", "u-video-1", "u-content-1"],
    createdBy: "u-manager",
    createdAt: ts(-40, 12),
  },
  {
    id: "p-3",
    name: "Oberoi Sky City — 3D Walkthrough",
    color: "#35B37E",
    clientName: "Oberoi Realty",
    services: ["3D Walkthrough Animation", "CGI Video", "Storyboard Video"],
    startDate: d(-12),
    deadline: d(35),
    description:
      "Photoreal 3D walkthrough of the 3BHK sample flat plus an exterior CGI reveal for the sales lounge.",
    status: "Active",
    priority: "High",
    leaderId: "u-tl-video",
    memberIds: ["u-3d-1", "u-video-1", "u-content-1"],
    createdBy: "u-admin",
    createdAt: ts(-12, 10),
  },
  {
    id: "p-4",
    name: "Godrej Emerald — Website Revamp",
    color: "#E0A325",
    clientName: "Godrej Properties",
    services: [
      "Website Design and Development",
      "Landing Page",
      "SEO Service",
      "Hosting",
    ],
    startDate: d(-6),
    deadline: d(45),
    description:
      "New microsite with a lead-capture landing page, on-page SEO and managed hosting.",
    status: "Planning",
    priority: "High",
    leaderId: "u-design-1",
    memberIds: ["u-web-1", "u-design-1", "u-content-1"],
    createdBy: "u-manager",
    createdAt: ts(-6, 15),
  },
  {
    id: "p-5",
    name: "Kalpataru Vienta — Channel Partner Meet",
    color: "#EC7C2A",
    clientName: "Kalpataru Limited",
    services: [
      "CP Meet Campaign",
      "Channel Partner Kit",
      "Brand PPT Creation",
      "Festival and Event Creative",
    ],
    startDate: d(-55),
    deadline: d(-8),
    description:
      "Channel partner meet at Sahara Star — invites, kit, deck and event creatives.",
    status: "Completed",
    priority: "Medium",
    leaderId: "u-tl-design",
    memberIds: ["u-design-1", "u-content-1", "u-bd-1"],
    createdBy: "u-admin",
    createdAt: ts(-55, 11),
  },
];

/* ------------------------------------------------------------------ tasks */

function session(
  id: string,
  userId: string,
  dayOffset: number,
  startH: number,
  durMin: number,
  endReason: TimeSession["endReason"],
  endNote?: string,
): TimeSession {
  const start = new Date();
  start.setDate(start.getDate() + dayOffset);
  start.setHours(startH, 0, 0, 0);
  const end = new Date(start.getTime() + durMin * 60_000);
  return {
    id,
    userId,
    startedAt: start.toISOString(),
    endedAt: end.toISOString(),
    endReason,
    endNote,
  };
}

/** An open session that started `minsAgo` minutes back — a live running timer. */
function openSession(id: string, userId: string, minsAgo: number): TimeSession {
  return {
    id,
    userId,
    startedAt: new Date(Date.now() - minsAgo * 60_000).toISOString(),
    endedAt: null,
    endReason: null,
  };
}

const tasks: Task[] = [
  /* ---- p-1 Lodha Amara ---- */
  {
    id: "t-1",
    projectId: "p-1",
    title: "Launch key visual — master creative",
    description:
      "Hero key visual for the Amara launch. Needs to work across hoarding, press and social crops.",
    department: "Graphic Designers",
    assigneeId: "u-design-1",
    status: "Approved",
    priority: "Critical",
    startDate: d(-22),
    dueDate: d(-16),
    estimatedHours: 14,
    tags: ["key-visual", "launch"],
    createdBy: "u-manager",
    createdAt: ts(-24, 11, 20),
    sessions: [
      session("s-1a", "u-design-1", -22, 10, 300, "End of day"),
      session("s-1b", "u-design-1", -21, 11, 270, "End of day"),
      session("s-1c", "u-design-1", -18, 10, 240, "Submitted"),
      session("s-1d", "u-design-1", -17, 12, 180, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-1a",
        byUserId: "u-design-1",
        at: ts(-18, 14),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/amara-kv-v1",
        description:
          "First cut of the key visual in three ratios. Typography still open for discussion.",
      },
      {
        id: "sub-1b",
        byUserId: "u-design-1",
        at: ts(-17, 15),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/amara-kv-v2",
        description:
          "Reworked with the client's typography note and a warmer sky grade.",
      },
    ],
    reviews: [
      {
        id: "rev-1a",
        submissionId: "sub-1a",
        byUserId: "u-manager",
        at: ts(-18, 17),
        decision: "Changes Required",
        source: "Client",
        remarks:
          "Client wants the tower to sit higher in the frame and the headline in their brand serif.",
      },
      {
        id: "rev-1b",
        submissionId: "sub-1b",
        byUserId: "u-manager",
        at: ts(-16, 11),
        decision: "Approved",
        remarks: "Approved as-is. Cleared for hoarding print.",
      },
    ],
    remarks: [
      {
        id: "rm-1a",
        byUserId: "u-design-1",
        at: ts(-19, 16),
        text: "Waiting on the final render from the 3D team for the tower plate.",
      },
    ],
  },
  {
    id: "t-2",
    projectId: "p-1",
    title: "Launch film — 60s edit",
    description:
      "Cut the launch film from the drone plates and the sample-flat footage. Needs Marathi and Hindi voice-over versions.",
    department: "Videographers / Video Editors / Motion Graphics",
    assigneeId: "u-video-1",
    status: "In Progress",
    priority: "Critical",
    startDate: d(-9),
    dueDate: d(3),
    estimatedHours: 26,
    tags: ["film", "launch", "voice-over"],
    createdBy: "u-manager",
    createdAt: ts(-10, 10),
    sessions: [
      session("s-2a", "u-video-1", -9, 10, 330, "End of day"),
      session("s-2b", "u-video-1", -8, 11, 240, "Switched", "Switched to Runwal Gardens — Monthly Retainer"),
      session("s-2c", "u-video-1", -3, 10, 285, "End of day"),
      openSession("s-2d", "u-video-1", 82),
    ],
    submissions: [],
    reviews: [],
    remarks: [
      {
        id: "rm-2a",
        byUserId: "u-video-1",
        at: ts(-3, 16),
        text: "Rough cut is locked. Starting the grade — VO records tomorrow.",
      },
    ],
  },
  {
    id: "t-3",
    projectId: "p-1",
    title: "Meta ads creative set — launch week",
    description: "9 static + 3 story creatives for the launch week burst.",
    department: "Graphic Designers",
    assigneeId: "u-design-2",
    status: "Submitted",
    priority: "High",
    startDate: d(-5),
    dueDate: d(1),
    estimatedHours: 12,
    tags: ["meta", "ads"],
    createdBy: "u-manager",
    createdAt: ts(-6, 9),
    sessions: [
      session("s-3a", "u-design-2", -5, 10, 300, "End of day"),
      session("s-3b", "u-design-2", -4, 10, 255, "End of day"),
      session("s-3c", "u-design-2", -1, 11, 195, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-3a",
        byUserId: "u-design-2",
        at: ts(-1, 15),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/amara-meta-set",
        description:
          "All 12 creatives exported. Copy locked with Ira. Story versions have safe-area guides.",
      },
    ],
    reviews: [],
    remarks: [],
  },
  {
    id: "t-4",
    projectId: "p-1",
    title: "Launch campaign copy deck",
    description: "Headlines, body copy and CTA variants for every launch surface.",
    department: "Content Writers / Copywriters / Brand Strategists",
    assigneeId: "u-content-1",
    status: "Approved",
    priority: "High",
    startDate: d(-20),
    dueDate: d(-14),
    estimatedHours: 10,
    tags: ["copy"],
    createdBy: "u-manager",
    createdAt: ts(-21, 10),
    sessions: [
      session("s-4a", "u-content-1", -20, 10, 240, "End of day"),
      session("s-4b", "u-content-1", -15, 11, 300, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-4a",
        byUserId: "u-content-1",
        at: ts(-15, 16),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/amara-copy-deck",
        description: "Copy deck with three headline routes and full CTA matrix.",
      },
    ],
    reviews: [
      {
        id: "rev-4a",
        submissionId: "sub-4a",
        byUserId: "u-manager",
        at: ts(-14, 12),
        decision: "Approved",
        remarks: "Route 2 selected by the client. Locked.",
      },
    ],
    remarks: [],
  },
  {
    id: "t-5",
    projectId: "p-1",
    title: "Performance media plan & pixel setup",
    description:
      "Budget split across Meta and Google, audience stack, and conversion pixel on the landing page.",
    department: "Performance Marketers",
    assigneeId: "u-perf-1",
    status: "Changes Required",
    priority: "High",
    startDate: d(-7),
    dueDate: d(2),
    estimatedHours: 8,
    tags: ["media-plan", "pixel"],
    createdBy: "u-manager",
    createdAt: ts(-8, 14),
    sessions: [
      session("s-5a", "u-perf-1", -7, 12, 210, "End of day"),
      session("s-5b", "u-perf-1", -2, 10, 165, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-5a",
        byUserId: "u-perf-1",
        at: ts(-2, 13),
        outputLocation: "WhatsApp",
        description:
          "Plan shared on the client group: ₹6L Meta / ₹4L Google over 4 weeks, CPL target ₹950.",
      },
    ],
    reviews: [
      {
        id: "rev-5a",
        submissionId: "sub-5a",
        byUserId: "u-manager",
        at: ts(-2, 18),
        decision: "Changes Required",
        source: "Project Leader",
        remarks:
          "Add a retargeting layer for site visitors and split the Google budget between Search and YouTube.",
      },
    ],
    remarks: [],
  },
  {
    id: "t-6",
    projectId: "p-1",
    title: "Hoarding artwork — Ghodbunder Road sites",
    description: "Adapt the key visual to the four booked hoarding sizes, print-ready.",
    department: "Graphic Designers",
    assigneeId: "u-design-1",
    status: "Not Started",
    priority: "High",
    startDate: d(1),
    dueDate: d(6),
    estimatedHours: 9,
    tags: ["hoarding", "print"],
    createdBy: "u-manager",
    createdAt: ts(-2, 11),
    sessions: [],
    submissions: [],
    reviews: [],
    remarks: [],
  },
  {
    id: "t-7",
    projectId: "p-1",
    title: "Launch week content calendar",
    description: "Day-wise posting plan across Instagram, Facebook and LinkedIn.",
    department: "Social Media Marketing",
    assigneeId: "u-smm-1",
    status: "In Progress",
    priority: "Medium",
    startDate: d(-3),
    dueDate: d(4),
    estimatedHours: 6,
    tags: ["calendar", "social"],
    createdBy: "u-manager",
    createdAt: ts(-3, 10),
    sessions: [session("s-7a", "u-smm-1", -1, 14, 150, "End of day")],
    submissions: [],
    reviews: [],
    remarks: [],
  },

  /* ---- p-2 Runwal Gardens ---- */
  {
    id: "t-8",
    projectId: "p-2",
    title: "October static post batch (16 creatives)",
    description: "Monthly static batch per the approved content calendar.",
    department: "Graphic Designers",
    assigneeId: "u-design-2",
    status: "Rejected",
    priority: "Medium",
    startDate: d(-18),
    dueDate: d(-4),
    estimatedHours: 20,
    tags: ["retainer", "static"],
    createdBy: "u-tl-design",
    createdAt: ts(-19, 10),
    sessions: [
      session("s-8a", "u-design-2", -18, 10, 300, "End of day"),
      session("s-8b", "u-design-2", -16, 11, 240, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-8a",
        byUserId: "u-design-2",
        at: ts(-16, 15),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/runwal-oct-statics",
        description: "All 16 statics, first pass.",
      },
    ],
    reviews: [
      {
        id: "rev-8a",
        submissionId: "sub-8a",
        byUserId: "u-tl-design",
        at: ts(-15, 11),
        decision: "Rejected",
        source: "Client",
        remarks:
          "Client rejected the batch — the template drifted from the brand book. Reassigning with the correct master file.",
        newAssigneeId: "u-design-1",
        newDueDate: d(2),
      },
    ],
    remarks: [],
  },
  {
    id: "t-9",
    projectId: "p-2",
    title: "Reel edit — amenity walkthrough",
    description: "30s vertical reel from the amenity deck footage.",
    department: "Videographers / Video Editors / Motion Graphics",
    assigneeId: "u-video-1",
    status: "Approved",
    priority: "Medium",
    startDate: d(-14),
    dueDate: d(-7),
    estimatedHours: 7,
    tags: ["reel"],
    createdBy: "u-tl-design",
    createdAt: ts(-14, 12),
    sessions: [
      session("s-9a", "u-video-1", -13, 15, 180, "End of day"),
      session("s-9b", "u-video-1", -8, 10, 210, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-9a",
        byUserId: "u-video-1",
        at: ts(-8, 14),
        outputLocation: "WhatsApp",
        description: "Reel shared on the client group for a quick look.",
      },
    ],
    reviews: [
      {
        id: "rev-9a",
        submissionId: "sub-9a",
        byUserId: "u-tl-design",
        at: ts(-7, 10),
        decision: "Approved",
        remarks: "Good pace. Scheduled for Thursday.",
      },
    ],
    remarks: [],
  },
  {
    id: "t-10",
    projectId: "p-2",
    title: "Community management — week 3",
    description: "Comment and DM responses across all handles.",
    department: "Social Media Marketing",
    assigneeId: "u-smm-1",
    status: "Not Started",
    priority: "Low",
    startDate: d(-1),
    dueDate: d(5),
    estimatedHours: 5,
    tags: ["community"],
    createdBy: "u-tl-design",
    createdAt: ts(-2, 9),
    sessions: [],
    submissions: [],
    reviews: [],
    remarks: [],
  },

  /* ---- p-3 Oberoi Sky City ---- */
  {
    id: "t-11",
    projectId: "p-3",
    title: "3BHK sample flat — white model & blockout",
    description: "Base geometry and camera paths for the walkthrough.",
    department: "3D Artists",
    assigneeId: "u-3d-1",
    status: "Submitted",
    priority: "High",
    startDate: d(-11),
    dueDate: d(-1),
    estimatedHours: 30,
    tags: ["3d", "walkthrough"],
    createdBy: "u-tl-video",
    createdAt: ts(-12, 10),
    sessions: [
      session("s-11a", "u-3d-1", -11, 10, 330, "End of day"),
      session("s-11b", "u-3d-1", -10, 10, 315, "End of day"),
      session("s-11c", "u-3d-1", -4, 11, 300, "End of day"),
      session("s-11d", "u-3d-1", -2, 10, 270, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-11a",
        byUserId: "u-3d-1",
        at: ts(-2, 15),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/skycity-blockout",
        description:
          "White model render + 4 camera path previews at 1080p. Awaiting sign-off before texturing.",
      },
    ],
    reviews: [],
    remarks: [
      {
        id: "rm-11a",
        byUserId: "u-3d-1",
        at: ts(-5, 12),
        text: "Balcony dimensions in the plan don't match the brochure — using the plan.",
      },
    ],
  },
  {
    id: "t-12",
    projectId: "p-3",
    title: "Walkthrough storyboard & shot list",
    description: "Beat-by-beat storyboard for the 90s walkthrough.",
    department: "Content Writers / Copywriters / Brand Strategists",
    assigneeId: "u-content-1",
    status: "Approved",
    priority: "Medium",
    startDate: d(-11),
    dueDate: d(-6),
    estimatedHours: 8,
    tags: ["storyboard"],
    createdBy: "u-tl-video",
    createdAt: ts(-12, 11),
    sessions: [session("s-12a", "u-content-1", -10, 10, 390, "Submitted")],
    submissions: [
      {
        id: "sub-12a",
        byUserId: "u-content-1",
        at: ts(-10, 17),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/skycity-storyboard",
        description: "14-panel storyboard with timings and VO cues.",
      },
    ],
    reviews: [
      {
        id: "rev-12a",
        submissionId: "sub-12a",
        byUserId: "u-tl-video",
        at: ts(-9, 10),
        decision: "Approved",
        remarks: "Locked. Sent to the 3D team as the camera brief.",
      },
    ],
    remarks: [],
  },
  {
    id: "t-13",
    projectId: "p-3",
    title: "Exterior CGI reveal — lighting pass",
    description: "Dusk lighting setup and the final beauty pass for the exterior reveal.",
    department: "3D Artists",
    assigneeId: "u-3d-1",
    status: "Not Started",
    priority: "High",
    startDate: d(2),
    dueDate: d(12),
    estimatedHours: 24,
    tags: ["cgi", "lighting"],
    createdBy: "u-tl-video",
    createdAt: ts(-1, 16),
    sessions: [],
    submissions: [],
    reviews: [],
    remarks: [],
  },

  /* ---- p-4 Godrej Emerald ---- */
  {
    id: "t-14",
    projectId: "p-4",
    title: "Microsite wireframes",
    description: "Wireframes for home, project detail, gallery and the lead form.",
    department: "Website Developers",
    assigneeId: "u-web-1",
    status: "In Progress",
    priority: "High",
    startDate: d(-4),
    dueDate: d(3),
    estimatedHours: 16,
    tags: ["wireframe", "web"],
    createdBy: "u-manager",
    createdAt: ts(-5, 10),
    sessions: [
      session("s-14a", "u-web-1", -4, 10, 300, "End of day"),
      session("s-14b", "u-web-1", -1, 11, 195, "End of day"),
    ],
    submissions: [],
    reviews: [],
    remarks: [],
  },
  {
    id: "t-15",
    projectId: "p-4",
    title: "SEO keyword map — Vikhroli micro-market",
    description: "Keyword clusters and on-page targets per URL.",
    department: "Performance Marketers",
    assigneeId: "u-perf-1",
    status: "Not Started",
    priority: "Medium",
    startDate: d(3),
    dueDate: d(9),
    estimatedHours: 7,
    tags: ["seo"],
    createdBy: "u-manager",
    createdAt: ts(-1, 11),
    sessions: [],
    submissions: [],
    reviews: [],
    remarks: [],
  },

  /* ---- p-5 Kalpataru (completed) ---- */
  {
    id: "t-16",
    projectId: "p-5",
    title: "CP meet invite & kit design",
    description: "Digital invite, printed kit folder and the on-stage backdrop.",
    department: "Graphic Designers",
    assigneeId: "u-design-1",
    status: "Approved",
    priority: "Medium",
    startDate: d(-50),
    dueDate: d(-40),
    estimatedHours: 18,
    tags: ["event", "print"],
    createdBy: "u-admin",
    createdAt: ts(-52, 10),
    sessions: [
      session("s-16a", "u-design-1", -50, 10, 330, "End of day"),
      session("s-16b", "u-design-1", -46, 10, 360, "End of day"),
      session("s-16c", "u-design-1", -42, 11, 300, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-16a",
        byUserId: "u-design-1",
        at: ts(-42, 16),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/kalpataru-cp-kit",
        description: "Invite, kit and backdrop, print-ready with bleed.",
      },
    ],
    reviews: [
      {
        id: "rev-16a",
        submissionId: "sub-16a",
        byUserId: "u-tl-design",
        at: ts(-41, 12),
        decision: "Approved",
        remarks: "Sent to press.",
      },
    ],
    remarks: [],
  },
  {
    id: "t-17",
    projectId: "p-5",
    title: "Brand deck for the CP presentation",
    description: "24-slide deck covering the project, pricing and the CP payout structure.",
    department: "Content Writers / Copywriters / Brand Strategists",
    assigneeId: "u-content-1",
    status: "Approved",
    priority: "High",
    startDate: d(-48),
    dueDate: d(-41),
    estimatedHours: 12,
    tags: ["deck"],
    createdBy: "u-admin",
    createdAt: ts(-49, 10),
    sessions: [
      session("s-17a", "u-content-1", -47, 10, 300, "End of day"),
      session("s-17b", "u-content-1", -44, 11, 285, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-17a",
        byUserId: "u-content-1",
        at: ts(-44, 16),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/kalpataru-deck",
        description: "Final deck, 24 slides, with speaker notes.",
      },
    ],
    reviews: [
      {
        id: "rev-17a",
        submissionId: "sub-17a",
        byUserId: "u-tl-design",
        at: ts(-43, 15),
        decision: "Approved",
        remarks: "Approved by the client's sales head.",
      },
    ],
    remarks: [],
  },

  /* ---- individual tasks (§10) ---- */
  {
    id: "t-18",
    projectId: null,
    title: "Refresh the agency showreel",
    description:
      "Cut a new 90s agency showreel from this quarter's best work for the new-business deck.",
    department: "Videographers / Video Editors / Motion Graphics",
    assigneeId: "u-video-1",
    status: "Not Started",
    priority: "Low",
    startDate: d(6),
    dueDate: d(16),
    estimatedHours: 12,
    tags: ["internal", "showreel"],
    createdBy: "u-admin",
    createdAt: ts(-3, 15),
    sessions: [],
    submissions: [],
    reviews: [],
    remarks: [],
  },
  {
    id: "t-19",
    projectId: null,
    title: "Q3 case-study one-pagers",
    description: "Three one-pagers for the pitch folder — Lodha, Runwal and Oberoi.",
    department: "Graphic Designers",
    assigneeId: "u-design-2",
    status: "In Progress",
    priority: "Medium",
    startDate: d(-2),
    dueDate: d(7),
    estimatedHours: 9,
    tags: ["internal", "collateral"],
    createdBy: "u-manager",
    createdAt: ts(-3, 10),
    sessions: [session("s-19a", "u-design-2", -2, 16, 120, "End of day")],
    submissions: [],
    reviews: [],
    remarks: [],
  },
  {
    id: "t-20",
    projectId: null,
    title: "Update the vendor rate card for FY26",
    description: "Collect revised rates from all active vendors and update the master sheet.",
    department: "Accounts & Finance",
    assigneeId: "u-finance",
    status: "Submitted",
    priority: "Medium",
    startDate: d(-8),
    dueDate: d(-2),
    estimatedHours: 6,
    tags: ["internal", "finance"],
    createdBy: "u-admin",
    createdAt: ts(-9, 11),
    sessions: [
      session("s-20a", "u-finance", -8, 11, 180, "End of day"),
      session("s-20b", "u-finance", -3, 10, 210, "Submitted"),
    ],
    submissions: [
      {
        id: "sub-20a",
        byUserId: "u-finance",
        at: ts(-3, 14),
        outputLocation: "Google Drive",
        driveLink: "https://drive.google.com/drive/folders/vendor-rate-card-fy26",
        description: "All five active vendors confirmed. Two rate increases flagged in red.",
      },
    ],
    reviews: [],
    remarks: [],
  },
  {
    id: "t-21",
    projectId: null,
    title: "Onboarding deck for new joiners",
    description: "Refresh the HR onboarding deck with the new org chart and tool list.",
    department: "Human Resources & Admin",
    assigneeId: "u-hr",
    status: "Not Started",
    priority: "Low",
    startDate: d(4),
    dueDate: d(11),
    estimatedHours: 5,
    tags: ["internal", "hr"],
    createdBy: "u-admin",
    createdAt: ts(-1, 10),
    sessions: [],
    submissions: [],
    reviews: [],
    remarks: [],
  },
];

const expenses: Database["expenses"] = [
  {
    id: "e-1",
    projectId: "p-1",
    vendorId: "v-1",
    description: "Drone shoot — Amara site, 2 days incl. edit-ready plates",
    amount: 36000,
    expenseDate: d(-13),
    attachmentName: "skylens-invoice-2418.pdf",
    status: "Approved",
    reviewedBy: "u-finance",
    reviewedAt: ts(-11, 12),
    createdBy: "u-manager",
    createdAt: ts(-13, 17),
  },
  {
    id: "e-2",
    projectId: "p-1",
    vendorId: "v-3",
    description: "Model casting — 2 models for the sample flat shoot",
    amount: 24000,
    expenseDate: d(-10),
    attachmentName: "cast-mumbai-inv-0912.pdf",
    status: "Pending",
    createdBy: "u-manager",
    createdAt: ts(-10, 18),
  },
  {
    id: "e-3",
    projectId: "p-1",
    vendorId: "v-5",
    description: "Marathi + Hindi voice-over for the launch film",
    amount: 13000,
    expenseDate: d(-2),
    status: "Pending",
    createdBy: "u-manager",
    createdAt: ts(-2, 16),
  },
  {
    id: "e-4",
    projectId: "p-2",
    vendorId: "v-2",
    description: "Amenity deck shoot — half-day crew",
    amount: 17500,
    expenseDate: d(-20),
    attachmentName: "framenine-inv-771.pdf",
    status: "Approved",
    reviewedBy: "u-finance",
    reviewedAt: ts(-18, 11),
    createdBy: "u-tl-design",
    createdAt: ts(-20, 17),
  },
  {
    id: "e-5",
    projectId: "p-5",
    vendorId: "v-4",
    description: "CP meet backdrop print + installation at Sahara Star",
    amount: 48000,
    expenseDate: d(-44),
    attachmentName: "signpost-inv-3310.pdf",
    status: "Rejected",
    financeRemarks:
      "Invoice is missing the GSTIN and the PO number. Please get a revised invoice from Signpost and re-submit.",
    reviewedBy: "u-finance",
    reviewedAt: ts(-42, 15),
    createdBy: "u-tl-design",
    createdAt: ts(-44, 18),
  },
  {
    id: "e-6",
    projectId: "p-3",
    vendorId: "v-2",
    description: "Reference photography of the sample flat for texturing",
    amount: 9500,
    expenseDate: d(-7),
    status: "Pending",
    createdBy: "u-tl-video",
    createdAt: ts(-7, 19),
  },
];

const projectTemplates: Database["projectTemplates"] = [
  {
    id: "pt-1",
    name: "Residential Project Launch",
    description:
      "Standard launch package for a new residential tower — creatives, film, paid media and outdoor.",
    color: "#5F3CA7",
    services: [
      "Project Launch Campaign Design",
      "Social Media Management Services",
      "Facebook Ads Campaign",
      "Google Ads",
      "Drone Shoot and Edit",
      "Hoarding Design and Conceptualization",
    ],
    priority: "High",
    durationDays: 45,
    createdAt: ts(-120, 10),
    tasks: [
      {
        id: "pti-1",
        title: "Brand & market immersion",
        description: "Study the micro-market, competition and the client's brand book.",
        department: "Content Writers / Copywriters / Brand Strategists",
        priority: "High",
        estimatedHours: 8,
        tags: ["research"],
        startOffsetDays: 0,
        durationDays: 3,
      },
      {
        id: "pti-2",
        title: "Campaign copy deck",
        description: "Headline routes, body copy and CTA matrix.",
        department: "Content Writers / Copywriters / Brand Strategists",
        priority: "High",
        estimatedHours: 10,
        tags: ["copy"],
        startOffsetDays: 3,
        durationDays: 4,
      },
      {
        id: "pti-3",
        title: "Launch key visual",
        description: "Master key visual working across hoarding, press and social.",
        department: "Graphic Designers",
        priority: "Critical",
        estimatedHours: 14,
        tags: ["key-visual"],
        startOffsetDays: 5,
        durationDays: 6,
      },
      {
        id: "pti-4",
        title: "Drone & site shoot",
        description: "Aerial plates and site footage for the launch film.",
        department: "Videographers / Video Editors / Motion Graphics",
        priority: "High",
        estimatedHours: 16,
        tags: ["shoot"],
        startOffsetDays: 8,
        durationDays: 3,
      },
      {
        id: "pti-5",
        title: "Launch film — 60s edit",
        description: "Edit, grade and voice-over for the launch film.",
        department: "Videographers / Video Editors / Motion Graphics",
        priority: "Critical",
        estimatedHours: 26,
        tags: ["film"],
        startOffsetDays: 12,
        durationDays: 8,
      },
      {
        id: "pti-6",
        title: "Ads creative set",
        description: "Static and story creatives for the launch burst.",
        department: "Graphic Designers",
        priority: "High",
        estimatedHours: 12,
        tags: ["ads"],
        startOffsetDays: 14,
        durationDays: 5,
      },
      {
        id: "pti-7",
        title: "Media plan & pixel setup",
        description: "Budget split, audience stack and conversion tracking.",
        department: "Performance Marketers",
        priority: "High",
        estimatedHours: 8,
        tags: ["media-plan"],
        startOffsetDays: 16,
        durationDays: 4,
      },
      {
        id: "pti-8",
        title: "Launch week content calendar",
        description: "Day-wise posting plan across all handles.",
        department: "Social Media Marketing",
        priority: "Medium",
        estimatedHours: 6,
        tags: ["calendar"],
        startOffsetDays: 20,
        durationDays: 3,
      },
    ],
  },
  {
    id: "pt-2",
    name: "Monthly Social Retainer",
    description: "Recurring monthly retainer: statics, reels and community management.",
    color: "#4B8FE6",
    services: [
      "Monthly Retainer",
      "Social Media Management Services",
      "Creative Post",
      "Reel Editing",
    ],
    priority: "Medium",
    durationDays: 30,
    createdAt: ts(-118, 10),
    tasks: [
      {
        id: "pti-9",
        title: "Monthly content calendar",
        description: "Plan the month's posts against the client's sales calendar.",
        department: "Social Media Marketing",
        priority: "Medium",
        estimatedHours: 6,
        tags: ["retainer", "calendar"],
        startOffsetDays: 0,
        durationDays: 2,
      },
      {
        id: "pti-10",
        title: "Static post batch (16)",
        description: "16 statics per the approved calendar.",
        department: "Graphic Designers",
        priority: "Medium",
        estimatedHours: 20,
        tags: ["retainer", "static"],
        startOffsetDays: 3,
        durationDays: 8,
      },
      {
        id: "pti-11",
        title: "Reel batch (8)",
        description: "8 vertical reels with captions and hooks.",
        department: "Videographers / Video Editors / Motion Graphics",
        priority: "Medium",
        estimatedHours: 18,
        tags: ["retainer", "reel"],
        startOffsetDays: 5,
        durationDays: 9,
      },
      {
        id: "pti-12",
        title: "Community management",
        description: "Comment and DM handling for the month.",
        department: "Social Media Marketing",
        priority: "Low",
        estimatedHours: 20,
        tags: ["retainer", "community"],
        startOffsetDays: 0,
        durationDays: 22,
      },
    ],
  },
  {
    id: "pt-3",
    name: "Website / Microsite Build",
    description: "Microsite build with a lead-capture landing page, SEO and hosting.",
    color: "#E0A325",
    services: [
      "Website Design and Development",
      "Landing Page",
      "SEO Service",
      "Hosting",
      "Domain",
    ],
    priority: "High",
    durationDays: 40,
    createdAt: ts(-100, 10),
    tasks: [
      {
        id: "pti-13",
        title: "Sitemap & wireframes",
        description: "Page inventory and wireframes for every template.",
        department: "Website Developers",
        priority: "High",
        estimatedHours: 16,
        tags: ["wireframe"],
        startOffsetDays: 0,
        durationDays: 5,
      },
      {
        id: "pti-14",
        title: "Visual design",
        description: "High-fidelity design for all templates, desktop and mobile.",
        department: "Graphic Designers",
        priority: "High",
        estimatedHours: 24,
        tags: ["ui"],
        startOffsetDays: 5,
        durationDays: 8,
      },
      {
        id: "pti-15",
        title: "Website copy",
        description: "Copy for every page plus meta titles and descriptions.",
        department: "Content Writers / Copywriters / Brand Strategists",
        priority: "Medium",
        estimatedHours: 12,
        tags: ["copy"],
        startOffsetDays: 5,
        durationDays: 6,
      },
      {
        id: "pti-16",
        title: "Build & integrate",
        description: "Front-end build, CMS and lead-form integration.",
        department: "Website Developers",
        priority: "Critical",
        estimatedHours: 40,
        tags: ["build"],
        startOffsetDays: 13,
        durationDays: 12,
      },
      {
        id: "pti-17",
        title: "SEO on-page & launch QA",
        description: "Keyword map, on-page tags, speed pass and pre-launch QA.",
        department: "Performance Marketers",
        priority: "High",
        estimatedHours: 10,
        tags: ["seo", "qa"],
        startOffsetDays: 25,
        durationDays: 5,
      },
    ],
  },
];

const taskTemplates: Database["taskTemplates"] = [
  {
    id: "tt-1",
    title: "Festival creative",
    description:
      "Single festival post adapted to the client's brand book. Include the logo lock-up and RERA line.",
    department: "Graphic Designers",
    priority: "Medium",
    estimatedHours: 3,
    tags: ["festival", "static"],
    startOffsetDays: 0,
    durationDays: 2,
    createdAt: ts(-90, 10),
  },
  {
    id: "tt-2",
    title: "Monthly performance report",
    description:
      "Spend, impressions, CPL and lead quality across Meta and Google, with next month's recommendation.",
    department: "Performance Marketers",
    priority: "Medium",
    estimatedHours: 4,
    tags: ["report"],
    startOffsetDays: 0,
    durationDays: 2,
    createdAt: ts(-88, 10),
  },
  {
    id: "tt-3",
    title: "Site walkthrough reel",
    description: "30s vertical reel from site footage with captions and a trending audio bed.",
    department: "Videographers / Video Editors / Motion Graphics",
    priority: "Medium",
    estimatedHours: 6,
    tags: ["reel"],
    startOffsetDays: 0,
    durationDays: 3,
    createdAt: ts(-85, 10),
  },
  {
    id: "tt-4",
    title: "Landing page build",
    description: "Single lead-capture landing page with form, thank-you state and pixel.",
    department: "Website Developers",
    priority: "High",
    estimatedHours: 14,
    tags: ["landing-page"],
    startOffsetDays: 0,
    durationDays: 5,
    createdAt: ts(-80, 10),
  },
];

/** A few real Indian public holidays plus an agency day. */
const holidays: Database["calendar"]["holidays"] = (() => {
  const year = new Date().getFullYear();
  return [
    { date: `${year}-01-26`, name: "Republic Day" },
    { date: `${year}-03-14`, name: "Holi" },
    { date: `${year}-05-01`, name: "Maharashtra Day" },
    { date: `${year}-08-15`, name: "Independence Day" },
    { date: `${year}-08-27`, name: "Ganesh Chaturthi" },
    { date: `${year}-10-02`, name: "Gandhi Jayanti" },
    { date: `${year}-10-20`, name: "Diwali — Lakshmi Pujan" },
    { date: `${year}-10-21`, name: "Diwali — Padwa" },
    { date: `${year}-12-25`, name: "Christmas" },
    { date: d(9), name: "Agency Foundation Day" },
  ];
})();

const notifications: Database["notifications"] = [
  {
    id: "n-1",
    userId: "u-manager",
    type: "task_submitted",
    title: "Task submitted for review",
    body: "Rahul Agarwal submitted “Meta ads creative set — launch week”.",
    href: "/tasks?task=t-3",
    read: false,
    createdAt: ts(-1, 15, 2),
  },
  {
    id: "n-2",
    userId: "u-perf-1",
    type: "review_decision",
    title: "Changes required",
    body: "Aditya Kulkarni asked for changes on “Performance media plan & pixel setup”.",
    href: "/tasks?task=t-5",
    read: false,
    createdAt: ts(-2, 18, 4),
  },
  {
    id: "n-3",
    userId: "u-design-1",
    type: "task_assigned",
    title: "Task reassigned to you",
    body: "“October static post batch (16 creatives)” was reassigned to you after a client rejection.",
    href: "/tasks?task=t-8",
    read: false,
    createdAt: ts(-15, 11, 3),
  },
  {
    id: "n-4",
    userId: "u-finance",
    type: "expense_added",
    title: "New expense to verify",
    body: "₹13,000 — Marathi + Hindi voice-over for the launch film (Lodha Amara).",
    href: "/expenses?expense=e-3",
    read: false,
    createdAt: ts(-2, 16, 5),
  },
  {
    id: "n-5",
    userId: "u-finance",
    type: "expense_added",
    title: "New expense to verify",
    body: "₹9,500 — Reference photography of the sample flat (Oberoi Sky City).",
    href: "/expenses?expense=e-6",
    read: false,
    createdAt: ts(-7, 19, 2),
  },
  {
    id: "n-6",
    userId: "u-manager",
    type: "expense_reviewed",
    title: "Expense approved",
    body: "Meera Joshi approved ₹36,000 for SkyLens Aerials.",
    href: "/expenses?expense=e-1",
    read: true,
    createdAt: ts(-11, 12, 1),
  },
  {
    id: "n-7",
    userId: "u-video-1",
    type: "timer_autostop",
    title: "Timer auto-stopped at 11:59 PM",
    body: "Your timer on “Launch film — 60s edit” was stopped automatically.",
    href: "/tasks?task=t-2",
    read: true,
    createdAt: ts(-4, 23, 59),
  },
  {
    id: "n-8",
    userId: "u-tl-video",
    type: "task_submitted",
    title: "Task submitted for review",
    body: "Pooja Sawant submitted “3BHK sample flat — white model & blockout”.",
    href: "/tasks?task=t-11",
    read: false,
    createdAt: ts(-2, 15, 6),
  },
  {
    id: "n-9",
    userId: "u-design-2",
    type: "due_soon",
    title: "Task due tomorrow",
    body: "“Meta ads creative set — launch week” is due tomorrow.",
    href: "/tasks?task=t-3",
    read: false,
    createdAt: ts(0, 9),
  },
];

export function seedDatabase(): Database {
  return {
    users,
    projects,
    tasks,
    expenses,
    vendors,
    projectTemplates,
    taskTemplates,
    calendar: {
      holidays,
      // HR has made one alternate Saturday a working day as an example override.
      workingOverrides: [],
    },
    notifications,
    lastAutoStopSweep: null,
  };
}

/** Convenience list for the login screen. */
export const DEMO_LOGINS = [
  { email: "super@synovative.in", password: "super123", label: "Super Admin" },
  { email: "admin@synovative.in", password: "admin123", label: "Admin" },
  { email: "manager@synovative.in", password: "manager123", label: "Manager" },
  { email: "hr@synovative.in", password: "hr123", label: "HR Admin" },
  { email: "karan@synovative.in", password: "karan123", label: "Team Leader" },
  {
    email: "finance@synovative.in",
    password: "finance123",
    label: "Accounts & Finance",
  },
  {
    email: "ashirwad@synovative.in",
    password: "ashirwad123",
    label: "Team Member",
  },
];
